"""empty message

Revision ID: 19345b57b0b9
Revises: 802f9fcf4f6c
Create Date: 2024-10-08 11:38:41.354114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19345b57b0b9'
down_revision = '802f9fcf4f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_vouch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario_scomprador', sa.Integer(), nullable=True),
    sa.Column('id_voucher_comprado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque_vouch')
    # ### end Alembic commands ###
