"""empty message

Revision ID: 2312aaf727d6
Revises: d694970252d9
Create Date: 2024-09-05 09:25:59.178160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2312aaf727d6'
down_revision = 'd694970252d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('qntd_cel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voucher')
    # ### end Alembic commands ###
