"""empty message

Revision ID: 324e4cd9f7e0
Revises: 97a3d6b1c0ad
Create Date: 2024-09-05 12:04:15.027773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324e4cd9f7e0'
down_revision = '97a3d6b1c0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuariop', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['id_usuariop'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_usuariop')

    # ### end Alembic commands ###
