"""empty message

Revision ID: 33902b0b141e
Revises: 2312aaf727d6
Create Date: 2024-09-05 09:29:30.971676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33902b0b141e'
down_revision = '2312aaf727d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
