"""empty message

Revision ID: 427675801f21
Revises: 19345b57b0b9
Create Date: 2024-10-17 08:14:21.616608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427675801f21'
down_revision = '19345b57b0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cartao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_endereco', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('id_endereco')
        batch_op.drop_column('id_cartao')

    # ### end Alembic commands ###
