"""empty message

Revision ID: 613f3086a46f
Revises: eda2c0111326
Create Date: 2024-10-25 13:43:46.754789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613f3086a46f'
down_revision = 'eda2c0111326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
