"""empty message

Revision ID: 7751e3f1c8c1
Revises: ccbb2d214a05
Create Date: 2024-11-07 10:46:44.107113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7751e3f1c8c1'
down_revision = 'ccbb2d214a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qntd_vendidas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_column('qntd_vendidas')

    # ### end Alembic commands ###
