"""empty message

Revision ID: 780646244e9a
Revises: 
Create Date: 2024-11-14 11:27:37.444057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780646244e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denuncias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('id_item', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_review', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_vouch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario_scomprador', sa.Integer(), nullable=True),
    sa.Column('id_voucher_comprado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('qntdestoque', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('preco_novo', sa.Float(), nullable=True),
    sa.Column('avaliacao', sa.Float(), nullable=True),
    sa.Column('qntd_vendidas', sa.Integer(), nullable=True),
    sa.Column('especial', sa.Integer(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('foto2', sa.String(), nullable=True),
    sa.Column('foto3', sa.String(), nullable=True),
    sa.Column('foto4', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_titular', sa.String(), nullable=False),
    sa.Column('num_cartao', sa.String(), nullable=False),
    sa.Column('data_vencimento', sa.String(), nullable=False),
    sa.Column('cvv', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario_comprador', sa.Integer(), nullable=True),
    sa.Column('id_item_comprado', sa.Integer(), nullable=True),
    sa.Column('qntd_comprado', sa.Integer(), nullable=True),
    sa.Column('preco_total_comprado', sa.Float(), nullable=True),
    sa.Column('id_cartao', sa.Integer(), nullable=True),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('celestianus', sa.Integer(), nullable=True),
    sa.Column('adm', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('qntd_cel', sa.Integer(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_itens', sa.Integer(), nullable=True),
    sa.Column('qntd_item', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_itens'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('sigla_estado', sa.String(), nullable=False),
    sa.Column('cep', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('estrela', sa.Integer(), nullable=False),
    sa.Column('Itens_id', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Itens_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('endereco')
    op.drop_table('carrinho')
    op.drop_table('voucher')
    op.drop_table('usuario')
    op.drop_table('reserva')
    op.drop_table('registro')
    op.drop_table('pagamento')
    op.drop_table('itens')
    op.drop_table('estoque_vouch')
    op.drop_table('denuncias')
    # ### end Alembic commands ###
