"""empty message

Revision ID: 851ca95bb977
Revises: 41c76072b42f
Create Date: 2024-10-24 09:49:14.724413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851ca95bb977'
down_revision = '41c76072b42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_de_entrega', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_column('forma_de_entrega')

    # ### end Alembic commands ###
