"""empty message

Revision ID: 85d77d4475ab
Revises: e091bdffd4c6
Create Date: 2024-11-13 14:55:47.699022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d77d4475ab'
down_revision = 'e091bdffd4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_item', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.drop_column('id_item')

    # ### end Alembic commands ###
