"""empty message

Revision ID: 920c8a8f7f2b
Revises: 0d2fb8b8a365
Create Date: 2024-09-14 13:10:09.109416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920c8a8f7f2b'
down_revision = '0d2fb8b8a365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denuncias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_review', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario_comprador', sa.Integer(), nullable=True),
    sa.Column('id_item_comprado', sa.Integer(), nullable=True),
    sa.Column('qntd_comprado', sa.Integer(), nullable=True),
    sa.Column('preco_total_comprado', sa.Float(), nullable=True),
    sa.Column('tempo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('registro')
    op.drop_table('denuncias')
    # ### end Alembic commands ###
