"""empty message

Revision ID: 951c5c4fe965
Revises: 98810a6d2485
Create Date: 2024-09-10 08:28:26.999935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951c5c4fe965'
down_revision = '98810a6d2485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_itens', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('id_itens')

    # ### end Alembic commands ###
