"""empty message

Revision ID: 98810a6d2485
Revises: 07b38f7e28a5
Create Date: 2024-09-10 08:27:16.438007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98810a6d2485'
down_revision = '07b38f7e28a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_itens', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'itens', ['id_itens'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_itens')

    # ### end Alembic commands ###
