"""empty message

Revision ID: 989ef099b2bb
Revises: 951c5c4fe965
Create Date: 2024-09-10 08:29:02.748999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989ef099b2bb'
down_revision = '951c5c4fe965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_itens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('id_itens')

    # ### end Alembic commands ###
