"""empty message

Revision ID: a840e6c1f6ce
Revises: 3fbfbb3559f2
Create Date: 2024-10-25 13:42:04.374485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a840e6c1f6ce'
down_revision = '3fbfbb3559f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
