"""empty message

Revision ID: bed5cfa52873
Revises: 37096ae3a8cd
Create Date: 2024-09-21 12:50:38.169857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed5cfa52873'
down_revision = '37096ae3a8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('Itens_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('Itens_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
