"""empty message

Revision ID: d694970252d9
Revises: 
Create Date: 2024-09-05 09:22:49.982894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd694970252d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('qntdestoque', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('avaliacao', sa.Float(), nullable=True),
    sa.Column('especial', sa.Integer(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('foto2', sa.String(), nullable=True),
    sa.Column('foto3', sa.String(), nullable=True),
    sa.Column('foto4', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_titular', sa.String(), nullable=False),
    sa.Column('num_cartao', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Integer(), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('celestianus', sa.Integer(), nullable=True),
    sa.Column('adm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_itens', sa.Integer(), nullable=True),
    sa.Column('qntd_item', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_itens'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('sigla_estado', sa.String(), nullable=False),
    sa.Column('cep', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    op.drop_table('carrinho')
    op.drop_table('usuario')
    op.drop_table('pagamento')
    op.drop_table('itens')
    # ### end Alembic commands ###
