"""empty message

Revision ID: e091bdffd4c6
Revises: 8f3b04ab0cf1
Create Date: 2024-11-07 10:56:33.425401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e091bdffd4c6'
down_revision = '8f3b04ab0cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.alter_column('avaliacao',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.alter_column('avaliacao',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
