"""empty message

Revision ID: ea7f63ce0154
Revises: 166bb27eaeb6
Create Date: 2024-09-10 08:23:00.706390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7f63ce0154'
down_revision = '166bb27eaeb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_Item', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'itens', ['id_Item'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_Item')

    # ### end Alembic commands ###
