"""empty message

Revision ID: f1807fd3a2fe
Revises: ea7f63ce0154
Create Date: 2024-09-10 08:25:01.329406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1807fd3a2fe'
down_revision = 'ea7f63ce0154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_itens', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'itens', ['id_itens'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_itens')

    # ### end Alembic commands ###
